######################################################################
# Automatically generated by qmake (2.01a) ?? 3. ??? 19:51:23 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
